const PERMISSIONS = {
    VIEW_ALL_VMS: 1 << 0,
    MANAGE_ALL_VMS: 1 << 1,
    MANAGE_CLIENT_USERS: 1 << 2,
    MANAGE_ADMIN_USERS: 1 << 3,
    CHANGE_CLIENT_PASSWORD: 1 << 4,
    CHANGE_ADMIN_PASSWORD: 1 << 5,
    MANAGE_ISO_FILES: 1 << 6,
    MANAGE_SYSTEM_RESOURCES: 1 << 7,
};

export default PERMISSIONS;
