services:
  cherry-admin-panel:
    container_name: cherry-admin-panel
    restart: always
    image: "ghcr.io/krzysztoff27/cherry-admin-panel:latest"
    networks:
      cherry-internal:
    user: "${SYSTEM_WORKER_UID:?error}:${SYSTEM_WORKER_UID:?error}"

networks:
  cherry-internal:
    name: cherry-internal
    external: true