services:
  database:
    container_name: cherry-db
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=${GUACAMOLE_USER}
      - POSTGRES_DB=${GUACAMOLE_DATABASE}
      - POSTGRES_PASSWORD=${GUACAMOLE_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data:rw
      - ./initdb:/docker-entrypoint-initdb.d/:ro
    networks:
      cherry-internal:
    user: "${SYSTEM_WORKER_UID:?error}:${SYSTEM_WORKER_UID:?error}"

networks:
  cherry-internal:
    name: cherry-internal
    external: true
