# syntax=docker/dockerfile:1.7-labs
FROM node:18-alpine

LABEL org.opencontainers.image.source=https://github.com/Krzysztoff27/Cherry-VM-Manager
LABEL org.opencontainers.image.description="Cherry Admin Panel"
LABEL org.opencontainers.image.licenses=CC-BY-NC-ND-4.0

WORKDIR /app

COPY ./package.json /app/package.json

RUN npm install
RUN npm i -g serve

COPY --exclude=./package.json --exclude=./docker ./ /app

RUN npm run build

EXPOSE 3000

CMD [ "serve", "-l", "3000", "-s", "dist" ]