services:
  guacamole:
      container_name: cherry-guacamole
      restart: always
      image: guacamole/guacamole
      environment:
        - GUACD_HOSTNAME=guacd
        - POSTGRESQL_HOSTNAME=database
        - POSTGRESQL_DATABASE=${GUACAMOLE_DATABASE}
        - POSTGRESQL_USER=${GUACAMOLE_USER}
        - POSTGRESQL_PASSWORD=${GUACAMOLE_PASSWORD}
      # If something stops working - I deleted links section (to other containers - should be obsolete)
      networks:
        cherry-internal:
      user: "${SYSTEM_WORKER_UID:?error}:${SYSTEM_WORKER_UID:?error}"

networks:
  cherry-internal:
    name: cherry-internal
    external: true