services:
  traefik:
    container_name: cherry-proxy
    restart: always
    image: traefik
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    command:
     #DELETE BEFORE RELEASING
     - "--log.level=DEBUG"
     #DELETE BEFORE RELEASING
     - "--api.dashboard=true"
     - "--providers.file.directory=/dynamic-configuration"
     - "--providers.file.watch=true"
     - "--entrypoints.web.address=:80"
     - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./dynamic-configuration:/dynamic-configuration"
    networks:
      cherry-external:
      cherry-internal:
        aliases:
          - ${DOMAIN_NAME}
    user: "${SYSTEM_WORKER_UID:?error}:${SYSTEM_WORKER_UID:?error}"

networks:
  cherry-external:
    name: cherry-external
    external: false
  cherry-internal:
    name: cherry-internal
    external: true