name: api_image

on:
    release:
        types:
            - published

jobs:
    #Check for a release wtith "target" property set to the API branch
    build-and-push:
        if: github.event.release.target_commitish == 'API'

        runs-on: ubuntu-latest

        permissions:
          contents: read
          packages: write

        env:
          OWNER: ${{ github.repository_owner }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
              
            - name: Downcase repository owner name
              run: |
                echo "OWNER=${OWNER,,}" >> "${GITHUB_ENV}"
            
            - name: Build Cherry-API Docker image
              run: |
                docker build \
                --file api/docker/dockerfile \
                --tag ghcr.io/${{ env.OWNER }}/cherry-api:${{ github.ref_name }} api
            
            - name: Push Cherry-API Docker image to GitHub Container Registry
              run: |
                docker push ghcr.io/${{ env.OWNER }}/cherry-api:${{ github.ref_name }}