http:
  routers:
    cvmm-traefik-router:
      rule: Host(`lenovo.lab`) && (PathPrefix(`/traefik`) || PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      service: api@internal
      entryPoints: web
      middlewares: auth
    cvmm-guacamole-guacamole-router:
      rule: "Host(`lenovo.lab`) && PathPrefix(`/guacamole`)"
      service: cvmm-guacamole-guacamole-service
      entryPoints: web

  middlewares:
      auth:
        basicAuth:
          users:
            - "test:$apr1$ssuQ3rCw$ls3xyHMqzgDXdhBXucGEp/"

  services:
    cvmm-guacamole-guacamole-service:
      loadBalancer:
        servers:
          - url: "http://cvmm-guacamole-guacamole:8080/guacamole"