http:
  routers:
    cvmm-traefik-router:
      rule: Host(`{{ printf "traefik.%s" (env "DOMAIN_NAME") }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      entryPoints: web
      middlewares: auth
    cvmm-guacamole-guacamole-router:
      rule: Host(`{{ env "DOMAIN_NAME" }}`) && PathPrefix(`/guacamole`)
      service: cvmm-guacamole-guacamole-service
      entryPoints: web

  middlewares:
      auth:
        basicAuth:
          users:
            - "CherryAdmin:$apr1$XAa8WkbY$XNs1zQjPVs.8lGKFuSYQV."

  services:
    cvmm-guacamole-guacamole-service:
      loadBalancer:
        servers:
          - url: "http://cvmm-guacamole-guacamole:8080/guacamole"