services:
  api:
    container_name: cherry-api
    # Possibly obsolete without TLS certificates
    # hostname: cherry-api
    restart: always
    image: "ghcr.io/krzysztoff27/cherry-api:latest"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - "/var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock:rw"
    networks:
      cherry-internal:
    user: "${SYSTEM_WORKER_UID:?error}:${SYSTEM_WORKER_UID:?error}"
  
networks:
  cherry-internal:
    name: cherry-internal
    external: true
